{
 "title": "FSpython",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "100ms",
 "templating": {
  "list": [
   {
    "name": "Database",
    "query": "\"FStemp\",\"FSrun1\",\"FSrun2\""
   },
   {
    "name": "Piloto",
    "query": "from(bucket: \"FStemp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"piloto\")"
   },
   {
    "name": "circuito",
    "query": "from(bucket: \"FStemp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuito\")"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Piloto - ${Piloto}\nCircuito - ${circuito}\n\n"
   },
   "targets": [
    {
     "query": "from(bucket: \"FStemp\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"piloto\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"data\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperaturas",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x301\" or r[\"_measurement\"] == \"0x302\" or r[\"_measurement\"] == \"0x303\")\r\n"
    }
   ]
  },
  {
   "title": "Temperaturas",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x301\" or r[\"_measurement\"] == \"0x302\" or r[\"_measurement\"] == \"0x303\")\r\n"
    }
   ]
  },
  { "type": "pr0ps-trackmap-panel", "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 } },
  {
   "title": "0x100 / Registro DC BUS VOLTAGE del inversor en la precarga",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x100\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 5, "x": 12, "y": 9 } },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x304\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x304\")\r\n  \r\n  \r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x104\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "0x103 / Sensor Freno",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x103\")\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value)} ))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x303\")\r\n  |> map(fn: (r) => ({r with _value: float(v: r._value)} ))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "ID_ack_precarga | 0x20",
     "type": "timeseries",
     "description": "Precarga lista y terminada",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x20\")"
      }
     ]
    },
    {
     "title": "ID_b_Iout | 0x450",
     "type": "timeseries",
     "description": "Corritente DC que sale del acumulador\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x450\")"
      }
     ]
    },
    {
     "title": "ID_dc_bus_voltage | 0x100",
     "type": "timeseries",
     "description": "Registro DC BUS VOLTAGE del inversor en la precarga\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x100\")"
      }
     ]
    },
    {
     "title": "Que es?? 0x12C",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x12C\")"
      }
     ]
    },
    {
     "title": "ID_t_motor | 0x301",
     "type": "timeseries",
     "description": "Temperatura del motor\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x301\")"
      }
     ]
    },
    {
     "title": "ID_t_air | 0x303",
     "type": "timeseries",
     "description": "Temperatura del aire en el inversor\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x303\")"
      }
     ]
    },
    {
     "title": "ID_corriente_inversor | 0x305",
     "type": "timeseries",
     "description": "no hay",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x305\")"
      }
     ]
    },
    {
     "title": "ID_t_igbt | 0x302",
     "type": "timeseries",
     "description": "Temperatura de los IGBT\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x302\")"
      }
     ]
    },
    {
     "title": "ID_sdd_suspension | 0x104",
     "type": "timeseries",
     "description": "Sensor Suspensión Delantera Derecha\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x104\")"
      }
     ]
    },
    {
     "title": "ID_torque_total | 0x106",
     "type": "timeseries",
     "description": "Torque porcentual solicitado al inversor\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x106\")"
      }
     ]
    },
    {
     "title": "ID_n_actual | 0x304",
     "type": "timeseries",
     "description": "Velocidad actual del motor\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x304\")"
      }
     ]
    },
    {
     "title": "ID_s_freno | 0x103",
     "type": "timeseries",
     "description": "Sensor Freno\n",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x103\")"
      }
     ]
    },
    {
     "title": "Que es?? 0x502",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "query": "from(bucket: ${Database})\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"0x502\")"
      }
     ]
    }
   ]
  }
 ]
}